apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactapp
  namespace: react
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: react
  project: default
  source:
    repoURL: 'https://github.com/sajadkamalinejad/react_gitops.git'
    path: /
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      selfHeal: true

